# Generated by Django 2.0.1 on 2018-03-03 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='detail',
            field=models.TextField(max_length=140),
        ),
    ]
